version: '3.8'

services:
  hermes:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./memory_storage:/app/memory_storage
    environment:
      - ALLOW_REMOTE=true
      - LOCAL_ONLY_LLM=true
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - ALLOW_EXTERNAL=true
      - CHROMA_REMOTE=false
      - CHROMA_PATH=/app/memory_storage
      - RAY_ADDRESS=ray://ray-head:10001
    depends_on:
      - chromadb
      - ray-head

  chromadb:
    image: chromadb/chroma
    volumes:
      - ./memory_storage:/chroma/memory_storage
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/memory_storage
    ports:
      - "8001:8000"

  ray-head:
    image: rayproject/ray
    ports:
      - "8265:8265"  # Ray dashboard
      - "10001:10001"  # Ray client server
    command: ray start --head --port=6379 --dashboard-port=8265 --redis-password=hermes_ray
    environment:
      - RAY_SERVE_ENABLE_EXPERIMENTAL_STREAMING=1

  ray-worker:
    image: rayproject/ray
    depends_on:
      - ray-head
    command: ray start --address=ray-head:6379 --redis-password=hermes_ray
    environment:
      - RAY_SERVE_ENABLE_EXPERIMENTAL_STREAMING=1
    deploy:
      replicas: 2
